### ISSUE TITLE
Integration documentation for Android and iOS is missing

### ISSUE THREAD

**Issue by mdaslamHossin** [readium/mobile#3]

**Comment by llemeurfr** [comment]
Can you be more precise please with this issue? at the moment it is not actionable.

**Comment by mdaslamHossin** [comment]
No doc found for integrating new application. That's why I arise this issue. If there any doc for proper guideline then close this issue.

**Comment by mickael-menu** [comment]
@mdaslamHossin There's no real documentation at the moment, usually people start from https://github.com/readium/r2-workspace-kotlin and look at https://github.com/readium/r2-testapp-kotlin for an example of integration.

However, we are currently improving the architecture to simplify the integration and will write a proper documentation and user guides once this is done.

In the meantime, you can take a look at https://github.com/readium/architecture for an overview of the architecture.

**Comment by mooka-ventures** [comment]
@mickael-menu - There is mention of " Audiobook support" - is there an demo example ?
Also what does Audiobook support mean - we don't want the text to speech conversion one, we have audiobooks created and we want to use that, is that possible to play using existing Readium app for iOS ?

**Comment by mickael-menu** [comment]
@mooka-ventures At the moment, R2 Kotlin is supporting Readium Audiobooks packages: https://readium.org/webpub-manifest/extensions/audiobook.html

This is basically a ZIP archive (or exploded directory on the web) of audio files, with a `manifest.json` describing the publication and the reading order. [Here's an example](https://readium.org/webpub-manifest/examples/Flatland/manifest.json).

We extended this support for simple ZAB (Zipped Audio Books) in the `alpha` branches. ZABs are ZIP archives of audio files, which will be read in the order of their filenames. What kind of audiobook format are you using?

For iOS, audiobooks support is not yet available but should be later this summer. Would you be interested in doing some beta–testing? You can get in touch with me [on our Slack channels](https://readium-slack.herokuapp.com/).

**Comment by mooka-ventures** [comment]
@mickael-menu  thanks. we are using normal mp3 files and we split the chapters in different mp3 files. but since the urls for the mp3 are generated dynamically we dont use a zipped archive of audio files style. manifest is a nice way to represent, we are doing part of such structure via our backend APIs. 

We will get back to you about your question on iOS audiobooks beta-testing.

**Comment by mickael-menu** [comment]
Once audiobooks are available, you will be able to play:

* A Readium Audiobook (packaged or from a single manifest)
* A ZIP archive with a list of audio files, sorted by filename (recursive)
* A directory containing audio files, sorted by filename (recursive)
* A single audio file

That should answer your needs. If you are serving the files from an HTTP server though, consider adding an [Audiobook RWP Manifest](https://readium.org/webpub-manifest/extensions/audiobook.html) too. This way your app will be able to read the audio files remotely just from the manifest URL, e.g. https://readium.org/webpub-manifest/examples/Flatland/manifest.json
