### ISSUE TITLE
Unable to find note/annotation option in iOS

### ISSUE THREAD

**Issue by gsindhupe** [readium/mobile#30]
I can see Note (annotation) option is available in menu when selected the text in Android, but when I am trying for the same option in iOS I can't see the Note option. Please let me know if it is available for iOS or if I am missing anything to unable the Note option for iOS

**Comment by HadrienGardeur** [comment]
Android and iOS have access to the same low-level API to support highlight/annotation through the [Decorator API](https://github.com/readium/architecture/blob/master/proposals/008-decorator-api.md).

If you're talking about the test app themselves, keep in mind that they are just meant to showcase some of what's possible in these toolkits, they're not reference implementations.

I'm closing this one, but you can re-open an issue or even submit a PR on the [swift-toolkit](https://github.com/readium/swift-toolkit) if you'd like to add this feature to the test app.
