### ISSUE TITLE
Error when downloading a publication: "Server seems not to support range requests to [address]"

### ISSUE THREAD

**Issue by mcpierce** [readium/mobile#37]
I'm working on a cross-platform iOS/Android reader, using Readium as the core for interacting with the server. The server is also a part of our project. We have navigating our library more or less working. However, when the reader attempts to download any publication from the server, we're seeing this error:

```Server seems not to support range requests to http://10.0.2.2:7171/opds/comics/245/content/comicbook.cbz.```

I'm not sure what API we should be providing, or what parameters we should be expecting, for the link to download a publication. Can you please point me to some documentation to let me know what's needed?

(edit for clarification) The above URL is one that works with other OPDS readers, such as Chunky. So I'm not sure what needs to be added to it in order to fulfill the request from Readium.

**Comment by HadrienGardeur** [comment]
Range requests are necessary for streaming publications, but not for downloading them.

What are you trying to build exactly with your app? An OPDS client that can download CBZ publications? Or the ability to stream them?

**Comment by mcpierce** [comment]
@HadrienGardeur For the reader's initial MVP we only need to download the publication. After it's released, I can see us adding streaming them.

**Comment by mickael-menu** [comment]
This is an error reported on Android when you're trying to stream an URL. You probably skipped the downloading step, which is not provided by the toolkit. You have to download the OPDS publication yourself. Here you tried to open an `http` URL instead of a local file with the `AssetRetriever`.

**Comment by mcpierce** [comment]
@HadrienGardeur The code is using an AssetRetriever. Here's the method in question:

```


    suspend fun doDownloadPublication(server: Server, url: String, reload: Boolean) {
        if (!reload) {
            Logger.d(TAG, "Skipping download: content found locally")
        } else {
            Logger.d(TAG, "Fetching content")
            val httpClient = createHttpClient(server)
            val assetRetriever = AssetRetriever(
                contentResolver = VariantApp.appContext.contentResolver,
                httpClient = httpClient
            )
            val absoluteUrl = AbsoluteUrl(url)
            Logger.d(TAG, "Retrieving asset: ${absoluteUrl}")

            val asset = assetRetriever.retrieve(
                absoluteUrl!!,
                FormatHints(
                    listOf(
                        "application/vnd.comicbook+zip",
                        "application/vnd.comicbook+rar",
                        "application/vnd.comicbook+octet-stream",
                    ), listOf("CBZ", "CBR", "CB7", "cbz", "cbr", "cb7")
                )
            )
                .onSuccess { thing ->
                    Logger.d(TAG, "Got my thing! ${thing}")
                }
                .onFailure { error ->
                    Logger.e(TAG, "Failed to open comic book: ${error}")
                }
        }
    }
```

Is this not the recommended way to retrieve publications using Readium? If it's the right way, then I'd be glad to add the appropriate API to our OPDS REST interface to download a range. I just need to know the specification for that expected API.

**Comment by qnga** [comment]
As Mickaël said, this piece of code reads the publication through range requests, it does not download it. Just use your `HttpClient` to download the publication to the file system and then pass an Url to the downloaded file to `assetRetriever.retrieve`. Then ranges will be read from your FS, not through HTTP.

**Comment by mcpierce** [comment]
@qnga Sorry if I'm not being clear: I'm asking if you guys can point me to a server-side example of how to provide the data to feed this API. Since our project manages that side of things as well, we can provide that if you could point us to an example of such a REST API.

**Comment by qnga** [comment]
Mmmm, if you want to modify a server to support publication streaming, see [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests). Readium doesn't do anything fancy but it's using standard HTTP range requests.

**Comment by mcpierce** [comment]
> Mmmm, if you want to modify a server to support publication streaming, see [this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests). Readium doesn't do anything fancy but it's using standard HTTP range requests.

Thank you! That's *exactly* what I was asking for. 😄
